print(bytearray())
print(bytearray(0))
print(bytearray(255))
print(bytearray(range(10)))
print(bytearray(10))
print(bytearray('jason', 'utf-8'))
print(bytearray(b'abcdef').replace(b'f', b'k'))
print(bytearray(b'abc').find(b'b'))
print(bytearray.fromhex('6162 6a 6b '))
print(bytearray('abc'.encode()).hex())
print(bytearray(b'abcdef')[2])

print('~' * 20)
b = bytearray()
b.append(97)
b.append(99)
b.append(65)
b.clear()
b.insert(1, 98)
print(b)
#b.remove(99)

