print(bytes())
print(bytes(11))
print(bytes(0))
print(bytes(255))
print(bytes('abc','utf-8'))
print(bytes('abc'.encode()))
print(bytes(b'abc'))

print(b'abdbdnjf'.replace(b'b', b'n'))
print(b'abdbdnjf'.find(b'n'))
print(bytes.fromhex('6162 09 6a 6b00'))
print('abc'.encode().hex())
print('abc'.encode())
print('abc'.encode().decode())
print('abc'.encode()[2])
print(b'abc'[2])